---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "Vndata@!@#$"
mysql_db: "wordpress"
mysql_user: "wordpress"
mysql_password: "Vndata@2020"

#HTTP Settings
http_host: "103.147.122.54"
http_conf: "54.conf"
http_port: "80"
